### ISSUE TITLE
Extract Unicode post content from XML dumps 

### ISSUE THREAD

**Issue by alerque** [alerque/stack-verse-mapper#6]
The XML data dumps is being extracted:

```
make hermeneutics
```

…should leave you with a file `hermeneutics.stackexchange.com/Posts.xml`. Next up we need something to parse this XML data and extract the body, then convert the XML leftovers into plain Unicode. I suspect flattening the rendered posts to a plain text version is going to be the way to go before passing it to the reference parser (see #2).

A script for this could:
- take an XML file as an argument
- parse the XML file for posts
- call another script with the post_id as an argument and the post body as stdin

**Comment by alerque** [comment]
@curiousdannii I'm leaving this part for you, but starting in on the next step myself. Right now I'm working in one script for both this and issue #2 leaving room for you to implement this at the top, but keep in mind as you implement the XML post parsing that at some point we might need to iterate over incoming data form other sources as well (for example the SE API to find posts that are newer than the last data dump). So logically keeping those two stages separate will make it easier to adapt the code later for wherever the data is coming from and whatever format it's in.

**Comment by swasheck** [comment]
I have a c# application that dumps to a sql table. If that'd help then I can pass that along

**Comment by alerque** [comment]
@swasheck Sure! Even if we can't/don't use the code directly a reference implementation might save us some shooting in the dark.
