### ISSUE TITLE
Strip out markup before looking for references

### ISSUE THREAD

**Issue by alerque** [alerque/stack-verse-mapper#8]
URLs have some crazy formatting and are giving a lot of false positives. I think the _useful_ data is going to be verse references which are named in the body of a post. Instead of feeding the whole rendered HTML post into the reference parser we strip the tags and flatten it to just a text post.

**Comment by curiousdannii** [comment]
The npm html-to-test package works great. I'd use it with these options

```
{
    wordwrap: false,
    ignoreHref: true,
}
```
